### ISSUE TITLE
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

### ISSUE THREAD

**Issue by DawidKos** [DawidKos/Casper#12]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python\Casper\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Python\Casper\main.py", line 34, in on_message
    await message.channel.send(bot.on_message(message))
  File "C:\Python\Casper\venv\lib\site-packages\discord\abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Python\Casper\venv\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
```

**Comment by DawidKos** [comment]
### Tymczasowy fix
Zastanówmy się jak to zrobić bez wywoływania dwukrotnie **gutenberg**a który musi przejrzeć wszystkie komendy
`    if message.author.bot is not True and str(message.channel) in interaction_channels:
        if type(bot.on_message(message)) is str:
            await message.channel.send(bot.on_message(message))`

**Comment by emiel73** [comment]
if message.content and message.author.bot is not True and str(message.channel) in interaction_channels: 
    await message.channel.send(bot.on_message(message))
